package cmd

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Scaffold a new driftgate test suite",
	RunE: func(cmd *cobra.Command, args []string) error {
		if err := os.MkdirAll(".driftgate", 0755); err != nil {
			return fmt.Errorf("create .driftgate directory: %w", err)
		}

		suite := `# .driftgate/suite.yaml
# Generated by: promptguard init

provider: anthropic
model: claude-haiku-4-5-20251001
timeout: 30s
concurrency: 5

tests:
  - name: "example test"
    tags: [smoke]
    prompt: "Say hello"
    assertions:
      - type: contains
        value: "hello"
        case_sensitive: false
`
		if err := os.WriteFile(".driftgate/suite.yaml", []byte(suite), 0644); err != nil {
			return fmt.Errorf("write suite file: %w", err)
		}
		fmt.Println("✓ Created .driftgate/suite.yaml")
		return nil
	},
}

func init() {
	rootCmd.AddCommand(initCmd)
}
